name: Run pip-compile

on:
  workflow_dispatch:

jobs:
  pip-compile:
    name: Run pip-compile
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repository
        uses: actions/checkout@v2.4.0

      - name: Run pip-compile
        run: |
          docker compose run --user="$(id -u):$(id -g)" -T pip-compile

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.12.1
        with:
          body: Update requirements with `pip-compile --upgrade`
          branch: pip-compile
          branch-suffix: random
          commit-message: Update requirements with `pip-compile --upgrade`
          delete-branch: true
          title: Update requirements with `pip-compile --upgrade`
